apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-restore-job
  namespace: cats
spec:
  template:
    spec:
      volumes:
        - name: nfs-backup-volume
          nfs:
            server: 192.168.178.35
            path: /srv/nfs/postgres-backup-cats-kubernetes
      containers:
        - name: postgres
          image: postgres:13-alpine
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password-secret
                  key: password
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: host
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: dbname
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: user
          volumeMounts:
            - name: nfs-backup-volume
              mountPath: /backup
          command: ["bash"]
          args: [
              "-c",
              "
              pg_restore
              --verbose
              --no-owner
              --clean
              --if-exists
              --dbname=$(PGDATABASE)
              /backup/$(PGDATABASE).sql.gz
              ",
            ]
      restartPolicy: Never
  backoffLimit: 1
