version: "3.8"

services:
  backup-cats-cronjob:
    image: postgres:alpine
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 1 * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
    volumes:
      - postgres-backup-restore-volume:/backup
    configs:
      - cats_postgres-user
      - cats_postgres-db
    secrets:
      - cats_postgres-password
    environment:
      PGHOST: db
    networks:
      - cats_cats
    command: >
      sh -c '
      PGPASSWORD=$$(cat /run/secrets/cats_postgres-password)
      pg_dump
      --dbname=$$(cat /cats_postgres-db)
      --username=$$(cat /cats_postgres-user)
      --verbose
      --no-owner
      --format=custom
      --file=/backup/$$(cat /cats_postgres-db).sql.gz'
volumes:
  postgres-backup-restore-volume:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.178.35,rw
      device: ":/srv/nfs/postgres-backup-cats-swarm"

networks:
  cats_cats:
    external: true

secrets:
  cats_postgres-password:
    external: true

configs:
  cats_postgres-user:
    external: true
  cats_postgres-db:
    external: true
