version: "3.3"

services:
  backup-cats-cronjob:
    image: postgres:alpine
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=* * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
    volumes:
      - postgres-backup-restore-volume:/backup
    configs:
      - cats_postgres-user
      - cats_postgres-db
    secrets:
      - cats_postgres-password

    environment:
      PGHOST: db

      POSTGRES_USER_FILE: /cats_postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/cats_postgres-password
      POSTGRES_DB_FILE: /cats_postgres-db

    command: >
      bash -c
        'export PGUSER=$$(cat $$POSTGRES_USER_FILE)
        PGDATABASE=$$(cat $$POSTGRES_DB_FILE) 
        && echo "*:*:*:*:$$(cat $$POSTGRES_PASSWORD_FILE)" > ~/.pgpass && chmod 0600 ~/.pgpass && pg_dump --verbose --no-owner --format=custom --file=/backup/$$(cat $$POSTGRES_DB_FILE).sql.gz'

volumes:
  postgres-backup-restore-volume:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.178.35,rw
      device: ":/srv/nfs/postgres-backup-cats-swarm"

networks:
  default:
    external:
      name: cats_default

secrets:
  cats_postgres-password:
    external: true

configs:
  cats_postgres-user:
    external: true
  cats_postgres-db:
    external: true
