version: "3.3"

services:

  app:
    image: linosthology/bachelor-thesis-example-combined-l1nus:1.0
    restart: on-failure
    ports:
      - ${PORT:-4000}:4000
    environment:
      PORT: 4000

      PGHOST: db
      PGPORT: 5432
      PGDATABASE: cats

      PGUSER: demo
      PGPASSWORD: ${POSTGRES_PASSWORD:-hcFWQgb5gDJA4EWw8Sp7}

  db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:${POSTGRES_PORT:-5432}:5432
    volumes: 
      - postgres-data:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hcFWQgb5gDJA4EWw8Sp7}
      POSTGRES_DB: cats

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.178.35,rw
      device: ":/srv/nfs/postgres-data-cats"
