version: "3.8"

services:
  backup-cats-cronjob:
    image: postgres:alpine
    deploy:
      mode: replicated-job
      replicas: 1
      max-concurrent: 1
      restart_policy:
        condition: none
    volumes:
      - postgres-backup-restore-volume:/backup
    configs:
      - cats_postgres-user
      - cats_postgres-db
    secrets:
      - cats_postgres-password

    environment:
      PGHOST: db

    command: >
      sh -c '
      export PGUSER=$$(cat /cats_postgres-user) &&
      export PGDATABASE=$$(cat /cats_postgres-db) &&
      echo "*:*:*:*:$$(cat /run/secrets/cats_postgres-password)" > ~/.pgpass &&
      chmod 0600 ~/.pgpass &&
      pg_restore
      --verbose 
      --no-owner 
      --clean 
      --if-exists 
      --dbname=${PGDATABASE} /backup/$${PGDATABASE}.sql.gz'

volumes:
  postgres-backup-restore-volume:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.178.35,rw
      device: ":/srv/nfs/postgres-backup-cats-swarm"

networks:
  default:
    external:
      name: cats_cats

secrets:
  cats_postgres-password:
    external: true

configs:
  cats_postgres-user:
    external: true
  cats_postgres-db:
    external: true
