apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-restore-job
spec:
  template:
    spec:
      volumes:
        - name: nfs-backup-volume
          nfs:
            server: 192.168.0.39
            path: /home/xenon/kubernetes/backup
        - name: db-password
          secret:
            secretName: postgres-password-secret
            defaultMode: 0600
      containers:
        - name: postgres
          image: postgres:13-alpine
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: host
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: dbname
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: user
          volumeMounts:
            - name: nfs-backup-volume
              mountPath: /backup
            - name: db-password
              mountPath: "/etc/db_password"
              readOnly: true
          command: ["bash"]
          args: [
              "-c",
              '
              echo "*:*:*:*:$(cat /etc/db_password/password)"
              > ~/.pgpass
              &&
              chmod 0600 ~/.pgpass
              &&
              pg_restore
              --verbose
              --no-owner
              --clean
              --if-exists
              --dbname=$(PGDATABASE)
              /backup/$(PGDATABASE).sql.gz
              ',
            ]
      restartPolicy: Never
  backoffLimit: 1
