# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    ports:
      - "6543:5432"
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: hcFWQgb5gDJA4EWw8Sp7
      POSTGRES_DB: cats
