apiVersion: v1
kind: Service
metadata:
  name: cats-service
  namespace: cats
  labels:
    app: cats
spec:
  type: LoadBalancer
  ports:
    - port: 4001
      targetPort: 4000
  selector:
    app: cats
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-deployment
  namespace: cats
  labels:
    app: cats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats
  template:
    metadata:
      labels:
        app: cats
    spec:
      volumes:
        - name: db-password
          secret:
            secretName: postgres-password-secret
            defaultMode: 0600
      containers:
        - name: cats
          volumeMounts:
            - name: db-password
              mountPath: "/etc/db_password"
              readOnly: true
          env:
            - name: PGUSER
              value: "demo"
            - name: PGHOST
              value: "postgres-service"
            - name: PGDATABASE
              value: "cats"
          image: linosthology/bachelor-thesis-example-combined-l1nus:1.0
          ports:
            - containerPort: 4000
          command: ["sh"]
          args: [
              "-c",
              '
              echo "*:*:*:*:$(cat /etc/db_password/password)"
              > ~/.pgpass
              &&
              chmod 0600 ~/.pgpass
              &&
              PORT=4000 node app.js
              ',
            ]