apiVersion: v1
kind: Service
metadata:
  name: cats-service
  labels:
    app: cats
spec:
  type: LoadBalancer
  ports:
    - port: 4001
      targetPort: 4001
  selector:
    app: cats
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-deployment
  labels:
    app: cats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats
  template:
    metadata:
      labels:
        app: cats
    spec:
      containers:
        - name: cats
          image: linusfr/bachelor-thesis-example:1.0-linusfr.duckdns.org-4001
          ports:
            - containerPort: 4001
          env:
            - name: PGUSER
              valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password-secret
                  key: password
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: host
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: dbname
            - name: PORT
              value: "4001"
