apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup-cronjob
  namespace: cats
spec:
  schedule: "* 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: nfs-backup-volume
              nfs:
                server: 192.168.178.35
                path: /srv/nfs/postgres-backup-cats-kubernetes
            - name: db-password
              secret:
                secretName: postgres-password-secret
                defaultMode: 0600
          containers:
            - name: postgres
              image: postgres:13-alpine
              env:
                - name: PGUSER
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-configmap
                      key: user
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-password-secret
                      key: password
                - name: PGHOST
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-configmap
                      key: host
                - name: PGDATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-configmap
                      key: dbname
              volumeMounts:
                - name: nfs-backup-volume
                  mountPath: /backup

              command: ["bash"]
              args: [
                  "-c",
                  "
                  pg_dump
                  --verbose
                  --no-owner
                  --format=custom
                  --file=/backup/$(PGDATABASE).sql.gz
                  ",
                ]
          restartPolicy: Never
